# 文件上传配置
file:
  upload:
    # 文件上传根路径（可以根据实际情况修改）
    base-path: /Users/tujunjie/Downloads/files
    # 文件访问URL前缀
    url-prefix: /file
    # 允许上传的文件类型
    allowed-types:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - txt
      - zip
      - rar
      - 7z
      - tar
      - gz
      - mp4
      - avi
      - mov
      - wmv
      - flv
      - mkv
      - mp3
      - wav
      - flac
      - aac
    # 单个文件最大大小（字节）10MB
    max-file-size: 10485760
    # 是否按日期分目录存储
    date-folder: true
    # 是否保留原文件名
    keep-original-name: false

# Spring配置
spring:
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 10MB
      # 总上传大小限制
      max-request-size: 100MB
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
