DROP TABLE IF EXISTS `recycle_order`;
CREATE TABLE `recycle_order` (
  `id` varchar(64) NOT NULL COMMENT '订单ID',
  `no` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `type` varchar(50) DEFAULT NULL COMMENT '订单类型',
  `status` varchar(20) DEFAULT NULL COMMENT '状态',
  `start_time` datetime DEFAULT NULL COMMENT '起始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `identify_code` varchar(100) DEFAULT NULL COMMENT '订单识别码',
  `processor` varchar(100) DEFAULT NULL COMMENT '经办人',
  `processor_phone` varchar(20) DEFAULT NULL COMMENT '经办人电话',
  `total_amount` decimal(15,2) DEFAULT NULL COMMENT '订单总金额',
  `order_node_time` datetime DEFAULT NULL COMMENT '订单节点时间',
  `order_node_img` varchar(500) DEFAULT NULL COMMENT '订单节点相关图片',
  `order_node_pickup_location` varchar(255) DEFAULT NULL COMMENT '提货位置',
  `order_node_delivery_location` varchar(255) DEFAULT NULL COMMENT '送货位置',
  `contract_no` varchar(100) DEFAULT NULL COMMENT '合同编号',
  `contract_name` varchar(200) DEFAULT NULL COMMENT '合同名称',
  `contract_partner` varchar(200) DEFAULT NULL COMMENT '合作方',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` varchar(1) DEFAULT '0' COMMENT '是否删除(0-未删除,1-已删除)',
  PRIMARY KEY (`id`),
  KEY `idx_no` (`no`),
  KEY `idx_contract_no` (`contract_no`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回收订单表';